import {
  getLanguage,
  type Language,
  type Locale,
  localeHref,
} from "@/lib/locales";

/**
 * Catalogue de textes, indexé par langue.
 *
 * La langue n'est plus lue dans `?lang=` : elle se déduit de la locale portée
 * par l'URL (voir src/lib/locales.ts). Les pages reçoivent donc leur locale
 * en paramètre de route et la convertissent ici.
 */

/** @deprecated Utiliser `Language` : ce type désignait la langue, pas la locale. */
export type { Language };

/** Langue déduite d'une locale d'URL (« fr-be » → « fr »). */
export function languageOf(locale?: string | null): Language {
  return getLanguage(locale);
}

/** @deprecated Le paramètre `?lang=` est redirigé vers le chemin par le middleware. */
export type SearchParams = Record<string, string | string[] | undefined>;

/** Préfixe un chemin par la locale courante. */
export function localizedHref(href: string, locale: Locale | string): string {
  return localeHref(href, locale);
}

export const nls = {
  fr: {
    common: {
      nav: {
        home: "Accueil",
        services: "Prestataires",
        community: "Communauté",
        game: "Jeux",
        contact: "Contact",
      },
      megaServices: {
        trigger: "Explorer",
        sections: {
          annuaire: "Annuaire",
          beaute: "Beauté",
          shopping: "Shopping & sorties",
          devenirPro: "Espace prestataire",
        },
        links: {
          all: "Tous les prestataires",
          allDesc: "Annuaire vérifié, toutes catégories",
          maquilleuses: "Maquilleuses",
          coiffeurs: "Coiffeurs & barbers",
          photographes: "Photographes",
          babysitting: "Babysitting",
          merch: "Merch & vendeurs",
          afters: "Afters & soirées",
          becomePro: "Devenir prestataire",
        },
      },
      quickNav: {
        aria: "Accès rapide",
        home: "Accueil",
        trajets: "Trajets",
        afters: "Afters",
        merch: "Merch",
        beaute: "Beauté",
        paris: "Paris pratique",
        game: "Sape Run",
        community: "Communauté",
      },
      vipCta: "Devenir prestataire",
      menu: "Navigation",
      openMenu: "Ouvrir le menu",
      seeMore: "Voir plus",
    },
    prestations: {
      number: "02",
      eyebrow: "Prestations",
      title: "Le centre du *style*.",
      description:
        "Trouve les prestataires utiles pour ton week-end. Les profils sont vérifiés sur base du portfolio.",
      members: "membres",
      explore: "Explorer la catégorie",
      proTitle: "Tu es prestataire ?",
      proDescription:
        "Nevent te donne une vitrine simple pour toucher les fans qui préparent leur week-end à Paris.",
      proCta: "S'inscrire comme pro",
      categories: [
        {
          title: "Maquilleuses",
          description: "Pros spécialisées peaux noires et métisses.",
        },
        {
          title: "Coiffeurs & barbers",
          description: "Tresses, lace wigs, coupes et dégradés propres.",
        },
        {
          title: "Photographes",
          description:
            "Portraits, groupes, événements et souvenirs du week-end.",
        },
        {
          title: "Babysitting",
          description:
            "Garde d'enfants pendant le concert, profils vérifiés par l'équipe.",
        },
      ],
    },
    game: {
      version: "Sape Run — v1.0",
      titleLine1: "Sape",
      titleLine2: "Run.",
      description:
        "Incarne l'Aigle et fonce vers la salle de concert ! Évite les obstacles, récupère les Micros d'Or et prouve que tu es le plus grand Warrior.",
      play: "Jouer maintenant",
      leaderboard: "Classement",
      weeklyLeaderboard: "Leaderboard hebdo",
      points: "PTS",
      updatedAt: "Dernière mise à jour à",
      emptyLeaderboard: "Aucun score cette semaine — sois le premier !",
      beFirst: "Lancer la première partie",
      back: "Retour au jeu",
      eyebrow: "Nevent × Sape Run",
      tagline:
        "Le Sapeur doit traverser la ville jusqu'à la salle de concert — aide-le !",
      idleTagline:
        "Aide le Sapeur à traverser la ville jusqu'à la salle de concert. Ramasse chapeaux, diamants et micros !",
      idleEyebrow: "Nevent Game",
      start: "Commencer",
      controlsHint: "Espace / Clic / Tap pour sauter",
      gameOver: "Game Over",
      fallen: "Le Sapeur est tombé !",
      score: "Score",
      record: "Record",
      newRecord: "Nouveau Record !",
      retry: "Rejouer",
      jumpHint: "Sauter (Espace / Clic)",
      recordLabel: "Record",
      speed: "VITESSE",
      goal: "LA SALLE",
      namePrompt: "Ton prénom (pour le classement)",
      namePlaceholder: "Ton prénom",
      nameRequired: "Entre ton prénom pour démarrer",
      playerLabel: "Joueur",
    },
    contact: {
      eyebrow: "Contact",
      title: "On reste *en ligne*.",
      description:
        "Une question sur un trajet, un paiement ou ton profil pro ? L'équipe Nevent te répond.",
      email: "Email",
      whatsapp: "WhatsApp Business",
      office: "Bureau",
      fullName: "Nom complet",
      fullNamePlaceholder: "Jean Dupont",
      subject: "Sujet",
      subjectHelp: "Pourquoi nous contactes-tu ?",
      subjectPlaceholder: "Covoiturage, partenariat...",
      message: "Message",
      messagePlaceholder: "Dis-nous tout...",
      send: "Envoyer le message",
    },
    footer: {
      headlineStart: "Rejoins",
      headlineMiddle: "fans de la diaspora.",
      headlineEnd: "Sans détour.",
      navigation: "Navigation",
      professionals: "Professionnels",
      legal: "Légal",
      rights: "TOUS DROITS RÉSERVÉS.",
      links: {
        rides: "Trajets",
        afters: "Afters",
        services: "Prestataires",
        photographers: "Photographes",
        proSpace: "Espace prestataire",
        partnerships: "Partenariats",
        ads: "Publicité",
        team: "L'équipe",
        contact: "Contact",
        faq: "FAQ",
        terms: "CGU",
        sales: "CGV",
        privacy: "Confidentialité",
        legalNotice: "Mentions légales",
        disclaimer: "Disclaimer",
      },
    },
    communityPage: {
      eyebrow: "Communauté",
      title: "Rejoins ta communauté WhatsApp",
      subtitle:
        "Une communauté par région, animée par des modérateurs Nevent. Entraide, infos concert, covoiturage, bons plans — tout est là.",
      cta: "Devenir modérateur de ta région",
      emptyTitle: "Bientôt disponible",
      emptyText:
        "Les premières communautés régionales arrivent. Postule comme modérateur pour lancer celle de ta ville.",
      membersLabel: "membres",
      joinButton: "Rejoindre",
      moderatedBy: "Animée par",
    },
  },
  en: {
    common: {
      nav: {
        home: "Home",
        services: "Providers",
        community: "Community",
        game: "Games",
        contact: "Contact",
      },
      megaServices: {
        trigger: "Explore",
        sections: {
          annuaire: "Directory",
          beaute: "Beauty",
          shopping: "Shop & nightlife",
          devenirPro: "Pro space",
        },
        links: {
          all: "All providers",
          allDesc: "Verified directory, all categories",
          maquilleuses: "Make-up artists",
          coiffeurs: "Hairdressers & barbers",
          photographes: "Photographers",
          babysitting: "Babysitting",
          merch: "Merch & sellers",
          afters: "Afters & parties",
          becomePro: "List my service",
        },
      },
      quickNav: {
        aria: "Quick access",
        home: "Home",
        trajets: "Rides",
        afters: "Afters",
        merch: "Merch",
        beaute: "Beauty",
        paris: "Paris guide",
        game: "Sape Run",
        community: "Community",
      },
      vipCta: "Become a pro",
      menu: "Navigation",
      openMenu: "Ouvrir le menu",
      seeMore: "Voir plus",
    },
    prestations: {
      number: "02",
      eyebrow: "Services",
      title: "The *style* hub.",
      description:
        "Find useful providers for your weekend. Profiles are checked through their portfolio.",
      members: "members",
      explore: "Explore category",
      proTitle: "Are you a provider?",
      proDescription:
        "Nevent gives you a simple storefront to reach fans preparing their Paris weekend.",
      proCta: "Register as a pro",
      categories: [
        {
          title: "Makeup artists",
          description: "Pros specialized in black and mixed skin.",
        },
        {
          title: "Hairdressers & barbers",
          description: "Braids, lace wigs, cuts and clean fades.",
        },
        {
          title: "Photographers",
          description: "Portraits, groups, events and weekend memories.",
        },
        {
          title: "Babysitting",
          description:
            "Childcare during the concert, profiles vetted by our team.",
        },
      ],
    },
    game: {
      version: "Sape Run — v1.0",
      titleLine1: "Sape",
      titleLine2: "Run.",
      description:
        "Jump, collect style bonuses and avoid obstacles to reach the venue at your best.",
      play: "Play now",
      leaderboard: "Leaderboard",
      weeklyLeaderboard: "Weekly leaderboard",
      points: "PTS",
      updatedAt: "Last updated at",
      emptyLeaderboard: "No scores this week — be the first!",
      beFirst: "Start the first run",
      back: "Back to game",
      eyebrow: "Nevent × Sape Run",
      tagline:
        "The Sapeur must cross the city all the way to the venue — help him!",
      idleTagline:
        "Help the Sapeur cross the city to reach the venue. Grab hats, diamonds and microphones!",
      idleEyebrow: "Nevent Game",
      start: "Start",
      controlsHint: "Space / Click / Tap to jump",
      gameOver: "Game Over",
      fallen: "The Sapeur is down!",
      score: "Score",
      record: "Best",
      newRecord: "New record!",
      retry: "Play again",
      jumpHint: "Jump (Space / Click)",
      recordLabel: "Best",
      speed: "SPEED",
      goal: "LA SALLE",
      namePrompt: "Your first name (for the leaderboard)",
      namePlaceholder: "Your first name",
      nameRequired: "Enter your first name to start",
      playerLabel: "Player",
    },
    contact: {
      eyebrow: "Contact",
      title: "Let's stay *connected*.",
      description:
        "Question about a ride, payment or pro profile? The Nevent team will reply.",
      email: "Email",
      whatsapp: "WhatsApp Business",
      office: "Office",
      fullName: "Full name",
      fullNamePlaceholder: "John Doe",
      subject: "Subject",
      subjectHelp: "Why are you contacting us?",
      subjectPlaceholder: "Carpool, partnership...",
      message: "Message",
      messagePlaceholder: "Tell us everything...",
      send: "Send message",
    },
    footer: {
      headlineStart: "Join",
      headlineMiddle: "diaspora fans.",
      headlineEnd: "No detours.",
      navigation: "Navigation",
      professionals: "Professionals",
      legal: "Legal",
      rights: "ALL RIGHTS RESERVED.",
      links: {
        rides: "Rides",
        afters: "Afters",
        services: "Providers",
        photographers: "Photographers",
        proSpace: "Provider area",
        partnerships: "Partnerships",
        ads: "Advertising",
        team: "Team",
        contact: "Contact",
        faq: "FAQ",
        terms: "Terms of use",
        sales: "Sales terms",
        privacy: "Privacy",
        legalNotice: "Legal notice",
        disclaimer: "Disclaimer",
      },
    },
    communityPage: {
      eyebrow: "Community",
      title: "Join your WhatsApp community",
      subtitle:
        "One community per region, run by Nevent moderators. Help, concert tips, carpooling, good deals — it's all here.",
      cta: "Become moderator of your region",
      emptyTitle: "Coming soon",
      emptyText:
        "The first regional communities are landing. Apply as moderator to launch yours.",
      membersLabel: "members",
      joinButton: "Join",
      moderatedBy: "Run by",
    },
  },
  de: {
    common: {
      nav: {
        home: "Start",
        services: "Anbieter",
        community: "Community",
        game: "Spiele",
        contact: "Kontakt",
      },
      megaServices: {
        trigger: "Entdecken",
        sections: {
          annuaire: "Verzeichnis",
          beaute: "Beauty",
          shopping: "Shopping & Nightlife",
          devenirPro: "Pro-Bereich",
        },
        links: {
          all: "Alle Dienstleister",
          allDesc: "Geprüftes Verzeichnis, alle Kategorien",
          maquilleuses: "Make-up Artists",
          coiffeurs: "Friseure & Barbiere",
          photographes: "Fotografen",
          babysitting: "Babysitting",
          merch: "Merch & Händler",
          afters: "Afters & Partys",
          becomePro: "Mein Angebot eintragen",
        },
      },
      quickNav: {
        aria: "Schnellzugriff",
        home: "Start",
        trajets: "Mitfahrten",
        afters: "Afters",
        merch: "Merch",
        beaute: "Beauty",
        paris: "Paris-Guide",
        game: "Sape Run",
        community: "Community",
      },
      vipCta: "Anbieter werden",
      menu: "Navigation",
      openMenu: "Menü öffnen",
      seeMore: "Mehr sehen",
    },
    prestations: {
      number: "02",
      eyebrow: "Services",
      title: "Das Zentrum für *Style*.",
      description:
        "Finde passende Dienstleister für dein Wochenende. Profile werden über das Portfolio geprüft.",
      members: "Mitglieder",
      explore: "Kategorie ansehen",
      proTitle: "Bist du Dienstleister?",
      proDescription:
        "Nevent gibt dir eine einfache Bühne, um Fans vor ihrem Paris-Wochenende zu erreichen.",
      proCta: "Als Profi anmelden",
      categories: [
        {
          title: "Make-up-Artists",
          description: "Profis für schwarze und gemischte Haut.",
        },
        {
          title: "Friseure & Barbiere",
          description: "Braids, Lace Wigs, Schnitte und saubere Fades.",
        },
        {
          title: "Fotografen",
          description: "Porträts, Gruppen, Events und Erinnerungen.",
        },
        {
          title: "Babysitting",
          description:
            "Kinderbetreuung während des Konzerts, vom Team geprüfte Profile.",
        },
      ],
    },
    game: {
      version: "Sape Run — v1.0",
      titleLine1: "Sape",
      titleLine2: "Run.",
      description:
        "Springe, sammle Style-Boni und weiche Hindernissen aus, um top gestylt zur Konzerthalle zu kommen.",
      play: "Jetzt spielen",
      leaderboard: "Rangliste",
      weeklyLeaderboard: "Wochenrangliste",
      points: "PKT",
      updatedAt: "Zuletzt aktualisiert um",
      emptyLeaderboard: "Diese Woche noch keine Scores — sei der Erste!",
      beFirst: "Erste Runde starten",
      back: "Zurück zum Spiel",
      eyebrow: "Nevent × Sape Run",
      tagline:
        "Der Sapeur muss durch die Stadt bis zur Konzerthalle — hilf ihm!",
      idleTagline:
        "Hilf dem Sapeur, durch die Stadt bis zur Konzerthalle zu kommen. Sammle Hüte, Diamanten und Mikros!",
      idleEyebrow: "Nevent Game",
      start: "Start",
      controlsHint: "Leertaste / Klick / Tap zum Springen",
      gameOver: "Game Over",
      fallen: "Der Sapeur ist gefallen!",
      score: "Punkte",
      record: "Rekord",
      newRecord: "Neuer Rekord!",
      retry: "Nochmal",
      jumpHint: "Springen (Leertaste / Klick)",
      recordLabel: "Rekord",
      speed: "TEMPO",
      goal: "LA SALLE",
      namePrompt: "Dein Vorname (für die Bestenliste)",
      namePlaceholder: "Dein Vorname",
      nameRequired: "Gib deinen Vornamen ein, um zu starten",
      playerLabel: "Spieler",
    },
    contact: {
      eyebrow: "Kontakt",
      title: "Wir bleiben *verbunden*.",
      description:
        "Frage zu Fahrt, Zahlung oder Profi-Profil? Das Nevent-Hub-Team antwortet dir.",
      email: "E-Mail",
      whatsapp: "WhatsApp Business",
      office: "Büro",
      fullName: "Vollständiger Name",
      fullNamePlaceholder: "Max Mustermann",
      subject: "Betreff",
      subjectHelp: "Warum kontaktierst du uns?",
      subjectPlaceholder: "Mitfahrgelegenheit, Partnerschaft...",
      message: "Nachricht",
      messagePlaceholder: "Erzähl uns alles...",
      send: "Nachricht senden",
    },
    footer: {
      headlineStart: "Schließ dich",
      headlineMiddle: "Diaspora-Fans an.",
      headlineEnd: "Direkt.",
      navigation: "Navigation",
      professionals: "Profis",
      legal: "Rechtliches",
      rights: "ALLE RECHTE VORBEHALTEN.",
      links: {
        rides: "Fahrten",
        afters: "Afters",
        services: "Anbieter",
        photographers: "Fotografen",
        proSpace: "Pro-Bereich",
        partnerships: "Partnerschaften",
        ads: "Werbung",
        team: "Team",
        contact: "Kontakt",
        faq: "FAQ",
        terms: "Nutzungsbedingungen",
        sales: "Verkaufsbedingungen",
        privacy: "Datenschutz",
        legalNotice: "Impressum",
        disclaimer: "Disclaimer",
      },
    },
    communityPage: {
      eyebrow: "Community",
      title: "Tritt deiner WhatsApp-Community bei",
      subtitle:
        "Eine Community pro Region, betreut von Nevent-Hub-Moderatoren. Hilfe, Konzertinfos, Mitfahrgelegenheiten, gute Tipps — alles da.",
      cta: "Werde Moderator deiner Region",
      emptyTitle: "Bald verfügbar",
      emptyText:
        "Die ersten regionalen Communities starten. Bewirb dich als Moderator, um deine zu eröffnen.",
      membersLabel: "Mitglieder",
      joinButton: "Beitreten",
      moderatedBy: "Geleitet von",
    },
  },
  nl: {
    common: {
      nav: {
        home: "Home",
        services: "Diensten",
        community: "Community",
        game: "Games",
        contact: "Contact",
      },
      megaServices: {
        trigger: "Ontdekken",
        sections: {
          annuaire: "Gids",
          beaute: "Beauty",
          shopping: "Shop & uitgaan",
          devenirPro: "Pro-ruimte",
        },
        links: {
          all: "Alle dienstverleners",
          allDesc: "Geverifieerde gids, alle categorieën",
          maquilleuses: "Make-up artists",
          coiffeurs: "Kappers & barbiers",
          photographes: "Fotografen",
          babysitting: "Babysitting",
          merch: "Merch & verkopers",
          afters: "Afters & feesten",
          becomePro: "Mijn dienst registreren",
        },
      },
      quickNav: {
        aria: "Snelle toegang",
        home: "Home",
        trajets: "Ritten",
        afters: "Afters",
        merch: "Merch",
        beaute: "Beauty",
        paris: "Parijs-gids",
        game: "Sape Run",
        community: "Community",
      },
      vipCta: "Aanbieder worden",
      menu: "Navigatie",
      openMenu: "Menu openen",
      seeMore: "Meer zien",
    },
    prestations: {
      number: "02",
      eyebrow: "Diensten",
      title: "Het centrum voor *style*.",
      description:
        "Vind handige dienstverleners voor je weekend. Profielen worden via portfolio gecontroleerd.",
      members: "leden",
      explore: "Categorie bekijken",
      proTitle: "Ben jij dienstverlener?",
      proDescription:
        "Nevent geeft je een eenvoudige etalage om fans te bereiken die hun Parijs-weekend voorbereiden.",
      proCta: "Inschrijven als pro",
      categories: [
        {
          title: "Make-up artists",
          description: "Pros gespecialiseerd in zwarte en gemengde huid.",
        },
        {
          title: "Kappers & barbiers",
          description: "Vlechten, lace wigs, coupes en strakke fades.",
        },
        {
          title: "Fotografen",
          description: "Portretten, groepen, events en weekendherinneringen.",
        },
        {
          title: "Babysitting",
          description:
            "Kinderopvang tijdens het concert, profielen door het team gecontroleerd.",
        },
      ],
    },
    game: {
      version: "Sape Run — v1.0",
      titleLine1: "Sape",
      titleLine2: "Run.",
      description:
        "Spring, verzamel style-bonussen en ontwijk obstakels om top gestyled de concertzaal te bereiken.",
      play: "Nu spelen",
      leaderboard: "Klassement",
      weeklyLeaderboard: "Weekklassement",
      points: "PTN",
      updatedAt: "Laatst bijgewerkt om",
      emptyLeaderboard: "Nog geen scores deze week — wees de eerste!",
      beFirst: "Start de eerste run",
      back: "Terug naar het spel",
      eyebrow: "Nevent × Sape Run",
      tagline: "De Sapeur moet door de stad naar de concertzaal — help hem!",
      idleTagline:
        "Help de Sapeur dwars door de stad tot de concertzaal. Pak hoeden, diamanten en microfoons!",
      idleEyebrow: "Nevent Game",
      start: "Start",
      controlsHint: "Spatie / Klik / Tap om te springen",
      gameOver: "Game Over",
      fallen: "De Sapeur is gevallen!",
      score: "Score",
      record: "Record",
      newRecord: "Nieuw record!",
      retry: "Opnieuw",
      jumpHint: "Springen (Spatie / Klik)",
      recordLabel: "Record",
      speed: "SNELHEID",
      goal: "LA SALLE",
      namePrompt: "Je voornaam (voor het klassement)",
      namePlaceholder: "Je voornaam",
      nameRequired: "Vul je voornaam in om te starten",
      playerLabel: "Speler",
    },
    contact: {
      eyebrow: "Contact",
      title: "We blijven *verbonden*.",
      description:
        "Vraag over een rit, betaling of pro-profiel? Het Nevent-team antwoordt.",
      email: "E-mail",
      whatsapp: "WhatsApp Business",
      office: "Kantoor",
      fullName: "Volledige naam",
      fullNamePlaceholder: "Jan Jansen",
      subject: "Onderwerp",
      subjectHelp: "Waarom neem je contact op?",
      subjectPlaceholder: "Carpool, partnership...",
      message: "Bericht",
      messagePlaceholder: "Vertel ons alles...",
      send: "Bericht versturen",
    },
    footer: {
      headlineStart: "Sluit je aan bij",
      headlineMiddle: "diaspora-fans.",
      headlineEnd: "Zonder omweg.",
      navigation: "Navigatie",
      professionals: "Professionals",
      legal: "Juridisch",
      rights: "ALLE RECHTEN VOORBEHOUDEN.",
      links: {
        rides: "Ritten",
        afters: "Afters",
        services: "Diensten",
        photographers: "Fotografen",
        proSpace: "Pro-zone",
        partnerships: "Partnerships",
        ads: "Advertenties",
        team: "Team",
        contact: "Contact",
        faq: "FAQ",
        terms: "Gebruiksvoorwaarden",
        sales: "Verkoopvoorwaarden",
        privacy: "Privacy",
        legalNotice: "Juridische kennisgeving",
        disclaimer: "Disclaimer",
      },
    },
    communityPage: {
      eyebrow: "Community",
      title: "Sluit je aan bij je WhatsApp-community",
      subtitle:
        "Eén community per regio, geleid door Nevent-moderators. Hulp, concertinfo, carpoolen, goede tips — alles is hier.",
      cta: "Word moderator van je regio",
      emptyTitle: "Binnenkort beschikbaar",
      emptyText:
        "De eerste regionale communities komen eraan. Solliciteer als moderator om die van jouw stad te starten.",
      membersLabel: "leden",
      joinButton: "Deelnemen",
      moderatedBy: "Geleid door",
    },
  },
} as const;

export type Dictionary = (typeof nls)[Language];
